title: 반짝임 프로젝트 - 기적, 빛나다
description: LOVE LIVE! SUNSHINE!! Aqours World LoveLive! ASIA TOUR 2019 in Seoul 기념 프로젝트
theme: just-the-docs

url: https://yousorail.github.io

aux_links:
  Twitter: https://x.com/AqoursInSEOUL
  YouTube: https://www.youtube.com/channel/UCNhIBsmxX1IsKCHroJbj8og

aux_links_new_tab: true

search_enabled: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "맨 위로 이동하기"
