title: 반짝임 프로젝트
description: LOVE LIVE! SUNSHINE!! Aqours World LoveLive! ASIA TOUR 2019 in Seoul 기념 프로젝트
theme: just-the-docs

url: https://yousorail.github.io

favicon_ico: "/assets/images/favicon.ico"

aux_links:
  Twitter: https://x.com/AqoursInSEOUL
  YouTube: https://www.youtube.com/channel/UCNhIBsmxX1IsKCHroJbj8og

aux_links_new_tab: true

search_enabled: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "맨 위로 이동하기"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%F" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

color_scheme: yousorail
